define({
    "loginBtn": "Войти",
    "registerBtn": "Зарегистрироваться",
    "or": "или",
    "logoutBtn": "Выход",
    "profileBtn": "Профиль",
    "support": "Техподдержка",
    "supportSite": "Сайт поддержки",
    "help": "Помогите!",
    "games": "Игры",
    "store": "Магазин",
    "forum": "Форум",
    "language": "Язык",
    "changePassword": "Сменить пароль",
    "purchaseHistory": "История покупок",
    "en": "english",
    "ru": "русский",
    "de": "deutsch",
    "fr": "français",
    "it": "italiano",
    "es": "español",
    "ja": "日本語",
    "ko": "한국어",
    "pl": "polski",
    "cs": "čeština",
    "pt": "português",
    "tr": "türkçe",
    "zh": "中文",
    "go_url": "?skin_lang=ru",
    "wt_url": "//warthunder.ru",
    "forum_wt_url": "//forum.warthunder.ru",
    "wiki_wt_url": "//wiki.warthunder.ru",
    "sc_url": "//star-conflict.com/ru",
    "forum_sc_url": "//forum.star-conflict.ru",
    "wiki_sc_url": "//wiki.star-conflict.ru",
    "xo_url": "//crossout.net/ru",
    "forum_xo_url": "//forum.crossout.ru",
    "live_url": "//live.warthunder.com/?lang=ru",
    "support_url": "//support.gaijin.net/hc/ru",
    "profile_link": "user.php?skin_lang=ru",
    "changeAccount": "Сменить аккаунт",
    "gaijin_link": "//gaijin.net/ru"
});